<?php

$apps_array = array(
    array(
        "title" => "Nextcloud",
        "category" => "Groupware",
        "description" => "Groupware, file sharing platform",
        "website" => "https://nextcloud.com",
        "image" => "nextcloud.png",
        "container_name" => "nextcloud",
        "external_hostname" => "cloud",
        "local_port" => 6443,
        "protocol" => "https://",
        "install" => "install_nextcloud.php",
        "update" => "post.php?update_nextcloud",
        "config" => "",
    ),
    array(
        "title" => "Jellyfin",
        "category" => "Media",
        "description" => "Turn your NAS into a media streaming platform for your Smart TVs, Smart devices (Roku, Amazon TV, Apple TV, Google TV), computers, phones etc",
        "website" => "https://jellyfin.com",
        "image" => "jellyfin.png",
        "container_name" => "jellyfin",
        "external_hostname" => "jellyfin",
        "local_port" => 8096,
        "protocol" => "http://",
        "install" => "install_jellyfin.php",
        "update" => "post.php?update_jellyfin",
        "config" => "",
    ),
    array(
        "title" => "PhotoPrism",
        "category" => "Media",
        "description" => "Manage Photos.",
        "website" => "https://photoprism.org",
        "image" => "photoprism.png",
        "container_name" => "photoprism",
        "external_hostname" => "photos",
        "local_port" => 2342,
        "protocol" => "http://",
        "install" => "install_photoprism.php",
        "update" => "post.php?update_photoprism",
        "config" => "",
    ),
    array(
        "title" => "Nginx Proxy Manager",
        "category" => "Proxy",
        "description" => "Proxy services from the outside in using LetsEncrypt Certs",
        "website" => "https://nginxproxymanager.com",
        "image" => "nginxproxymanager.png",
        "container_name" => "nginx-proxy-manager",
        "external_hostname" => "proxy",
        "local_port" => 83,
        "protocol" => "http://",
        "install" => "post.php?install_nginx-proxy-manager",
        "update" => "post.php?update_nginx-proxy-manager",
        "config" => "",
    ),
    array(
        "title" => "DAAPD",
        "category" => "Media",
        "description" => "iTunes Server Music Streaming App",
        "website" => "https://ejurgensen.github.io/forked-daapd/",
        "image" => "daapd.png",
        "container_name" => "daapd",
        "external_hostname" => "",
        "local_port" => 3689,
        "protocol" => "http://",
        "install" => "install_daapd.php",
        "update" => "post.php?update_daapd",
        "config" => "",
    ),
    array(
        "title" => "Transmission",
        "category" => "Downloads",
        "description" => "Web based BitTorrent Download Client",
        "website" => "https://transmission.org",
        "image" => "transmission.png",
        "container_name" => "transmission",
        "external_hostname" => "transmission",
        "local_port" => 9091,
        "protocol" => "http://",
        "install" => "install_transmission.php",
        "update" => "",
        "config" => "configure_transmission.php",
    ),
    array(
        "title" => "Bitwarden RS",
        "category" => "Password Manager",
        "description" => "Password Manager -- Note: Bitwarden will not work properly unless remote access is enabled because Bitwarden requires HTTPS.",
        "website" => "https://bitwarden.org",
        "image" => "bitwarden.png",
        "container_name" => "bitwarden",
        "external_hostname" => "vault",
        "local_port" => 88,
        "protocol" => "http://",
        "install" => "post.php?install_bitwarden",
        "update" => "post.php?update_bitwarden",
        "config" => "",
    ),
    array(
        "title" => "Home Assistant",
        "category" => "Smart Home",
        "description" => "Home Automation (Control Lights, switches, smart devices etc)",
        "website" => "https://homeassistant.com",
        "image" => "homeassistant.png",
        "container_name" => "homeassistant",
        "external_hostname" => "homeassistant",
        "local_port" => 8123,
        "protocol" => "http://",
        "install" => "post.php?install_homeassistant",
        "update" => "post.php?update_homeassistant",
        "config" => "",
    ),
    array(
        "title" => "Unifi Controller",
        "category" => "Unifi Apps",
        "description" => "Manage Ubiquiti network devices.",
        "website" => "https://dokuwiki.com",
        "image" => "unifi.png",
        "container_name" => "unifi-controller",
        "external_hostname" => "unifi",
        "local_port" => 8443,
        "protocol" => "https://",
        "install" => "post.php?install_unifi-controller",
        "update" => "post.php?update_unifi-controller",
        "config" => "",
    )
);

$file = file_get_contents('ServiceTemplate.txt');

foreach ($apps_array as $app) {
    $appFile = $file;
    $app["title_clean"] = str_replace(' ', '', $app['title']);
    foreach ($app as $key => $value) {
        $appFile = str_replace('<%'.$key.'%>', $value, $appFile);
    }
    file_put_contents($app["title_clean"], $appFile);
}
